# Generated by Django 5.2.1 on 2025-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musictour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizzatore',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='organizzatore',
            name='id_organizzatore',
        ),
        migrations.RemoveField(
            model_name='organizzatore',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='partecipante',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='partecipante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='partecipante',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='partecipante',
            name='password',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='is_organizzatore',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='is_partecipante',
        ),
        migrations.AddField(
            model_name='organizzatore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='utente',
            name='ruolo',
            field=models.CharField(choices=[('partecipante', 'Partecipante'), ('organizzatore', 'Organizzatore'), ('entrambi', 'Entrambi')], default='partecipante', max_length=20),
        ),
    ]
